-- CS Quiz user profiles, attempts and leaderboard.
-- Run this once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category_id text not null,
  category_name text not null,
  total_questions integer not null check (total_questions > 0),
  correct_answers integer not null default 0,
  incorrect_answers integer not null default 0,
  skipped_answers integer not null default 0,
  score numeric not null default 0,
  percentage numeric not null default 0,
  time_limit_minutes integer not null default 20,
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists quiz_attempts_user_id_idx on public.quiz_attempts(user_id);
create index if not exists quiz_attempts_score_idx on public.quiz_attempts(percentage desc, score desc);

alter table public.profiles enable row level security;
alter table public.quiz_attempts enable row level security;

drop policy if exists "Profiles are public" on public.profiles;
create policy "Profiles are public" on public.profiles for select to anon, authenticated using (true);

drop policy if exists "Users create own profile" on public.profiles;
create policy "Users create own profile" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "Users can read own attempts" on public.quiz_attempts;
create policy "Users can read own attempts" on public.quiz_attempts for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own attempts" on public.quiz_attempts;
create policy "Users can create own attempts" on public.quiz_attempts for insert to authenticated with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace view public.leaderboard as
select
  p.id as user_id,
  p.display_name,
  count(a.id)::integer as attempts_count,
  max(a.percentage) as best_percentage,
  max(a.score) as best_score
from public.profiles p
join public.quiz_attempts a on a.user_id = p.id
group by p.id, p.display_name;

grant select on public.profiles to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.quiz_attempts to authenticated;
grant select on public.leaderboard to anon, authenticated;
