import React from 'react'
import { ArrowRight, BrainCircuit, CheckCircle2, Clock3, Database, Menu, Play, Trophy, X } from 'lucide-react'
import { LanguageToggle, t } from './i18n'

const highlights = [
  { icon: Database, title: 'TRE Computer Science Subjects', text: 'Practice DSA, DBMS, OS, Networks, Programming and other core CS topics.' },
  { icon: Clock3, title: 'BPSC TRE Exam Practice', text: 'Build speed and accuracy with focused, timed Computer Science quizzes.' },
  { icon: Trophy, title: 'Track Your Performance', text: 'Review mistakes, explanations and identify the topics that need more practice.' },
]

export default function Home({ onStart, onCategories, language, onLanguageChange }) {
  const [menuOpen, setMenuOpen] = React.useState(false)
  const closeMenu = () => setMenuOpen(false)
  const x = key => t(language, key)
  return <div className="home-page">
    <header className="navbar home-navbar">
      <button className="brand brand-button" onClick={() => { closeMenu(); window.scrollTo({ top: 0, behavior: 'smooth' }) }} aria-label="Go to home"><span className="brand-mark"><BrainCircuit size={21} /></span><span>BPSC TRE <span className="brand-accent">CS</span></span></button>
      <nav className={`home-links ${menuOpen ? 'is-open' : ''}`}>
        <a className="active" href="#home" onClick={closeMenu}>{x('Home')}</a><button onClick={() => { closeMenu(); onCategories() }}>{x('Subjects')}</button><a href="#features" onClick={closeMenu}>{x('Features')}</a><a href="#about" onClick={closeMenu}>{x('About')}</a>
      </nav>
      <div className="home-nav-actions"><LanguageToggle lang={language} onChange={onLanguageChange} /><button className="home-nav-cta" onClick={() => { closeMenu(); onStart() }}>{x('Start Practice')} <ArrowRight size={16} /></button><button className="mobile-menu home-mobile-menu" onClick={() => setMenuOpen(v => !v)} aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></div>
    </header>
    <main id="home">
      <section className="home-hero"><div className="hero-copy"><span className="eyebrow"><BrainCircuit size={15} /> BPSC TRE · Computer Science</span><h1>Prepare smarter.<br /><span>Crack BPSC TRE.</span></h1><p>{language === 'hi' ? 'BPSC Teacher Recruitment Exam के लिए Computer Science की focused practice करें। Concepts मजबूत करें, speed बढ़ाएँ और exam confidence बनाएं।' : 'Focused Computer Science practice for BPSC Teacher Recruitment Exam aspirants. Strengthen concepts, improve speed and build exam confidence one question at a time.'}</p><div className="hero-actions"><button className="primary-btn large" onClick={onStart}>{x('Start practicing')} <ArrowRight size={18} /></button><button className="secondary-btn large" onClick={onCategories}>{x('Explore subjects')}</button></div><div className="hero-trust"><CheckCircle2 size={16} /><span>{x('Instant results')}</span><i /><span>{x('Detailed explanations')}</span><i /><span>{x('TRE focused')}</span></div></div><div className="hero-visual"><div className="hero-orbit orbit-a" /><div className="hero-orbit orbit-b" /><div className="hero-quiz-card"><div className="mini-top"><span>BPSC TRE PRACTICE</span><b>01 / 10</b></div><div className="mini-progress"><span /></div><small>Data Structures</small><h3>Which data structure is best suited for implementing recursion?</h3><div className="mini-option"><b>A</b> Stack</div><div className="mini-option"><b>B</b> Queue</div><div className="mini-option"><b>C</b> Linked List</div><div className="mini-option"><b>D</b> Heap</div><button onClick={onStart}><Play size={13} fill="currentColor" /> {x('Start practice')}</button></div></div></section>
      <section className="home-stats"><div><strong>11+</strong><span>{x('Core CS Subjects')}</span></div><div><strong>120+</strong><span>{x('Practice Questions')}</span></div><div><strong>24/7</strong><span>{x('Self Practice')}</span></div></section>
      <section className="home-features" id="features"><div className="home-section-head"><span className="kicker">WHY BPSC TRE CS</span><h2>{x('Practice with a purpose.')}</h2><p>{language === 'hi' ? 'Computer Science concepts को exam-ready confidence में बदलने के लिए जरूरी tools।' : 'Everything you need to turn Computer Science concepts into exam-ready confidence.'}</p></div><div className="feature-grid">{highlights.map(({ icon: Icon, title, text }) => <article key={title}><div className="feature-icon"><Icon size={21} /></div><h3>{language === 'hi' ? ({'TRE Computer Science Subjects':'TRE कंप्यूटर साइंस विषय','BPSC TRE Exam Practice':'BPSC TRE परीक्षा अभ्यास','Track Your Performance':'अपना प्रदर्शन देखें'}[title] || title) : title}</h3><p>{language === 'hi' ? ({'Practice DSA, DBMS, OS, Networks, Programming and other core CS topics.':'DSA, DBMS, OS, Networks, Programming और अन्य core CS topics का अभ्यास करें.','Build speed and accuracy with focused, timed Computer Science quizzes.':'Focused और timed Computer Science quizzes से speed और accuracy बढ़ाएँ.','Review mistakes, explanations and identify the topics that need more practice.':'अपनी गलतियाँ और explanations देखें और कमजोर topics पहचानें.'}[text] || text) : text}</p><button onClick={onCategories}>{x('Explore subjects')} <ArrowRight size={15} /></button></article>)}</div></section>
      <section className="home-exam" id="about"><div><span className="kicker">{x('BPSC TRE PREPARATION')}</span><h2>{x('One platform focused on Computer Science.')}</h2><p>{language === 'hi' ? 'BPSC TRE Computer Science की तैयारी के लिए core subjects का अभ्यास करें।' : 'Practice core subjects with questions designed around BPSC TRE Computer Science preparation.'}</p></div><button onClick={onStart}>{x('Start TRE practice')} <ArrowRight size={17} /></button></section>
    </main><footer className="footer"><span>© 2026 BPSC TRE CS. Computer Science practice platform.</span><span><a href="#home">{x('Home')}</a><a href="#features">{x('Features')}</a><LanguageToggle lang={language} onChange={onLanguageChange} /></span></footer>
  </div>
}
