import React from 'react'
import { ArrowLeft, ArrowRight, BrainCircuit, Check, Clock3, Flag, Pause, Play, RotateCcw, X } from 'lucide-react'
import { questionBank } from './data/questionBank'
import { LanguageToggle } from './i18n'

const categoryNames = {
  'computer-fundamentals':'Computer Fundamentals','data-structures':'Data Structures & Algorithms','database-management':'Database Management','operating-system':'Operating System','computer-networks':'Computer Networks',programming:'Programming','computer-organization':'Computer Organization','compiler-design':'Compiler Design','software-engineering':'Software Engineering','artificial-intelligence':'Artificial Intelligence','cyber-security':'Cyber Security','exam-practice':'BPSC TRE Full Mock'
}
const fallbackQuestions = [
  {id:'fallback-1',topic:'Computer Science',question:'Which data structure follows FIFO order?',options:['Stack','Queue','Tree','Heap'],answer:1,explanation:'A queue follows First In, First Out (FIFO).',difficulty:'Easy'},
  {id:'fallback-2',topic:'Computer Science',question:'Which language is primarily used to style web pages?',options:['HTML','CSS','SQL','C'],answer:1,explanation:'CSS is used to style and control presentation.',difficulty:'Easy'},
  {id:'fallback-3',topic:'Computer Science',question:'Which protocol is connection-oriented?',options:['UDP','IP','TCP','ARP'],answer:2,explanation:'TCP provides connection-oriented reliable delivery.',difficulty:'Medium'}
]
const shuffle = items => [...items].sort(() => Math.random() - .5)
const prepareQuestions = pool => shuffle(pool).map(q => { const opts=shuffle(q.options.map((option,index)=>({option,index}))); return {...q,options:opts.map(x=>x.option),answer:opts.findIndex(x=>x.index===q.answer)} })

export default function QuizApp({onHome,categoryId,language,onLanguageChange}) {
  const isFullMock=categoryId==='exam-practice'
  const bankQuestions=isFullMock?Object.values(questionBank).flat():(questionBank[categoryId]||[])
  const pool=bankQuestions.length?bankQuestions:fallbackQuestions
  const [quizMinutes,setQuizMinutes]=React.useState(isFullMock?60:20)
  const [timeInput,setTimeInput]=React.useState(String(isFullMock?60:20))
  const questions=React.useMemo(()=>prepareQuestions(pool).slice(0,Math.min(isFullMock?50:100,pool.length)),[categoryId,isFullMock])
  const [started,setStarted]=React.useState(false),[paused,setPaused]=React.useState(false),[current,setCurrent]=React.useState(0),[answers,setAnswers]=React.useState({}),[marked,setMarked]=React.useState([]),[seconds,setSeconds]=React.useState(quizMinutes*60),[submitted,setSubmitted]=React.useState(false),[reviewFilter,setReviewFilter]=React.useState('all')
  React.useEffect(()=>{if(!started||submitted||paused)return;const timer=setInterval(()=>setSeconds(v=>Math.max(v-1,0)),1000);return()=>clearInterval(timer)},[started,submitted,paused])
  React.useEffect(()=>{if(started&&seconds===0)setSubmitted(true)},[seconds,started])
  const total=questions.length, answered=Object.keys(answers).length, correct=questions.filter((q,i)=>answers[i]===q.answer).length, incorrect=questions.filter((q,i)=>answers[i]!==undefined&&answers[i]!==q.answer).length, skipped=total-answered
  const rawScore=correct-(isFullMock?incorrect*.25:0), score=Math.max(0,rawScore), percentage=total?Math.round(score/total*100):0
  const formatTime=v=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`
  const startQuiz=()=>{const minutes=isFullMock?60:Math.max(1,Math.min(180,Number(timeInput)||20));setQuizMinutes(minutes);setSeconds(minutes*60);setPaused(false);setStarted(true)}
  const reset=()=>{setStarted(false);setPaused(false);setCurrent(0);setAnswers({});setMarked([]);setSeconds(quizMinutes*60);setSubmitted(false);setReviewFilter('all')}
  const header=<header className="quiz-header"><button className="brand brand-button" onClick={onHome}><span className="brand-mark"><BrainCircuit size={21}/></span><span>BPSC TRE <span className="brand-accent">CS</span></span></button><div className="quiz-title">{categoryNames[categoryId]||'Computer Science'} Practice</div><LanguageToggle lang={language} onChange={onLanguageChange}/></header>
  if(!questions.length)return <div className="quiz-app">{header}<main className="result-page"><section className="result-hero"><h1>No questions available</h1><button className="primary-btn" onClick={onHome}>Back</button></section></main></div>
  if(submitted){const performance=percentage>=80?'Excellent performance!':percentage>=60?'Good job — keep improving.':percentage>=40?'Nice attempt — more practice will help.':'Keep practicing — you will improve.';const filtered=questions.filter((q,i)=>reviewFilter==='correct'?answers[i]===q.answer:reviewFilter==='incorrect'?answers[i]!==undefined&&answers[i]!==q.answer:reviewFilter==='skipped'?answers[i]===undefined:true);return <div className="quiz-app">{header}<main className="result-page"><section className="result-hero"><div className="result-kicker">QUIZ COMPLETED · {(categoryNames[categoryId]||'COMPUTER SCIENCE').toUpperCase()}</div><div className="score-ring"><strong>{Number.isInteger(score)?score:score.toFixed(2)}</strong><span>Score / {total}</span></div><h1>{performance}</h1><p>You scored <b>{Number.isInteger(score)?score:score.toFixed(2)}</b> out of <b>{total}</b>.</p>{isFullMock&&<p className="negative-marking-note">Negative marking: <b>−0.25</b> for each incorrect answer.</p>}<div className="result-stats"><div><strong>{correct}</strong><span>Correct</span></div><div><strong>{incorrect}</strong><span>Incorrect</span></div><div><strong>{skipped}</strong><span>Skipped</span></div><div><strong>{percentage}%</strong><span>Percentage</span></div></div><div className="result-actions"><button className="primary-btn" onClick={reset}><RotateCcw size={17}/> Try again</button><button className="secondary-btn" onClick={onHome}><ArrowLeft size={17}/> Home</button></div></section><section className="review-section"><span className="result-kicker">ANSWER REVIEW</span><h2>Review your performance</h2><div className="review-tabs">{[['all','All',total],['correct','Correct',correct],['incorrect','Incorrect',incorrect],['skipped','Skipped',skipped]].map(([k,l,c])=><button className={reviewFilter===k?'active':''} onClick={()=>setReviewFilter(k)} key={k}>{l}<span>{c}</span></button>)}</div><div className="review-list">{filtered.map(q=>{const i=questions.indexOf(q),u=answers[i],ok=u===q.answer,skip=u===undefined;return <article className={`review-item ${ok?'review-correct':skip?'review-skipped':'review-incorrect'}`} key={q.id}><div className="review-item-top"><span className="review-number">Q{i+1}</span><span className="question-label">{q.topic}</span><span className="review-status">{ok?<><Check size={14}/> Correct</>:skip?<><Flag size={14}/> Skipped</>:<><X size={14}/> Incorrect</>}</span></div><h3>{q.question}</h3><div className="review-answers"><div className="review-answer"><span>Your answer</span><strong>{skip?'Not answered':`${String.fromCharCode(65+u)}. ${q.options[u]}`}</strong></div><div className="review-answer correct-answer"><span>Correct answer</span><strong>{String.fromCharCode(65+q.answer)}. {q.options[q.answer]}</strong></div></div><div className="explanation"><strong>Explanation</strong><p>{q.explanation}</p></div></article>})}</div></section></main></div>}
  if(!started)return <div className="quiz-app">{header}<main className="quiz-start"><div className="start-copy"><div className="eyebrow"><BrainCircuit size={15}/> {isFullMock?'BPSC TRE · Full Mock Test':`${categoryNames[categoryId]||'Computer Science'} practice`}</div><h1>{isFullMock?<>BPSC TRE CS <span>Full Mock Test</span>.</>:<>Test your <span>{categoryNames[categoryId]||'Computer Science'}</span> knowledge.</>}</h1><p>{total} questions focused on {categoryNames[categoryId]||'Computer Science'}. Answer all questions and get instant results.</p>{!isFullMock&&<div className="time-picker-card"><div className="time-picker-heading"><div className="time-picker-icon"><Clock3 size={19}/></div><div><h2>Set your time</h2><p>Choose how much time you want for this quiz.</p></div></div><div className="time-input-wrap"><button type="button" onClick={()=>setTimeInput(String(Math.max(1,(Number(timeInput)||20)-5)))}>−</button><div className="time-input-value"><input type="number" min="1" max="180" value={timeInput} onChange={e=>setTimeInput(e.target.value)}/><span>min</span></div><button type="button" onClick={()=>setTimeInput(String(Math.min(180,(Number(timeInput)||20)+5)))}>+</button></div><div className="time-presets-label">Quick select</div><div className="time-presets">{[10,20,30,45,60].map(m=><button key={m} type="button" className={Number(timeInput)===m?'active':''} onClick={()=>setTimeInput(String(m))}>{m}<span>min</span></button>)}</div></div>}<div className="start-details"><div><Clock3 size={18}/><span><b>{isFullMock?60:Math.max(1,Number(timeInput)||20)} min</b> time limit</span></div><div><Flag size={18}/><span><b>{total}</b> questions</span></div><div><Check size={18}/><span><b>{isFullMock?'−0.25':'+1'}</b> {isFullMock?'negative / wrong':'mark / question'}</span></div></div><button className="primary-btn large" onClick={startQuiz}>{isFullMock?'Start full mock':'Start quiz'} <ArrowRight size={18}/></button></div><div className="preview-card"><div className="preview-top"><span>{isFullMock?'BPSC TRE CS · FULL MOCK':'QUIZ PREVIEW'}</span><b>{total} QUESTIONS</b></div><div className="preview-progress"><span/></div><small>Question 1 of {total}</small><h3>{questions[0].question}</h3>{questions[0].options.map((o,i)=><div className="preview-option" key={o}><b>{String.fromCharCode(65+i)}</b>{o}</div>)}</div></main></div>
  const question=questions[current]
  return <div className="quiz-app"><header className="quiz-header"><button className="brand brand-button" onClick={onHome}><span className="brand-mark"><BrainCircuit size={21}/></span><span>BPSC TRE <span className="brand-accent">CS</span></span></button><div className="live-meta"><span>{categoryNames[categoryId]||'Computer Science'} · Question {current+1} / {total}</span><span className={seconds<60?'timer danger':'timer'}><Clock3 size={16}/> {formatTime(seconds)}</span><LanguageToggle lang={language} onChange={onLanguageChange}/><button className="secondary-btn" onClick={()=>setPaused(v=>!v)}>{paused?<><Play size={15}/> Resume</>:<><Pause size={15}/> Pause</>}</button></div></header><main className="quiz-layout"><section className="question-panel"><div className="question-top"><div><span className="question-label">{question.topic}</span><p>Question {current+1} of {total}</p></div><div className="question-tools"><button className={marked.includes(current)?'mark-btn marked':'mark-btn'} onClick={()=>setMarked(v=>v.includes(current)?v.filter(i=>i!==current):[...v,current])}><Flag size={16}/> {marked.includes(current)?'Marked':'Mark for review'}</button></div></div><div className="progress-line"><span style={{width:`${(current+1)/total*100}%`}}/></div><h1>{question.question}</h1><div className="answers">{question.options.map((o,i)=><button className={answers[current]===i?'answer selected':'answer'} onClick={()=>setAnswers(v=>({...v,[current]:i}))} key={o}><span>{String.fromCharCode(65+i)}</span><strong>{o}</strong>{answers[current]===i&&<Check size={18}/>}</button>)}</div><div className="question-nav"><button className="secondary-btn" disabled={!current} onClick={()=>setCurrent(v=>v-1)}><ArrowLeft size={17}/> Previous</button>{current===total-1?<button className="primary-btn" onClick={()=>setSubmitted(true)}>Submit quiz <Check size={17}/></button>:<button className="primary-btn" onClick={()=>setCurrent(v=>v+1)}>Next question <ArrowRight size={17}/></button>}</div></section><aside className="question-sidebar"><div className="sidebar-head"><span>QUESTIONS</span><strong>{answered}/{total}</strong></div><div className="question-grid">{questions.map((q,i)=><button className={`${answers[i]!==undefined?'answered ':''}${i===current?'current ':''}${marked.includes(i)?'review':''}`} onClick={()=>setCurrent(i)} key={q.id}>{i+1}</button>)}</div><div className="legend"><span><i className="dot answered-dot"/>Answered</span><span><i className="dot review-dot"/>Review</span><span><i className="dot"/>Not visited</span></div><button className="submit-side" onClick={()=>setSubmitted(true)}>Submit quiz</button></aside>{paused&&<div className="quiz-pause-overlay"><div className="quiz-pause-card"><div className="time-picker-icon"><Pause size={24}/></div><h2>Quiz Paused</h2><p>Your progress is saved. The timer is stopped.</p><button className="primary-btn" onClick={()=>setPaused(false)}><Play size={17}/> Resume Quiz</button></div></div>}</main></div>
}
